# Generated by Django 5.0.1 on 2024-02-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_rename_bio_author_name_alter_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(blank=True, default='First Name', max_length=40, null=True),
        ),
    ]
